# Generated by Django 6.0.3 on 2026-03-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_highlighted_snippet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
